// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: idlmap.sql

package db

import (
	"context"
)

const getIdlmapByName = `-- name: GetIdlmapByName :one
SELECT id, svcname, idl, type, created_at FROM idlmap
WHERE svcname = $1 LIMIT 1
`

func (q *Queries) GetIdlmapByName(ctx context.Context, svcname string) (Idlmap, error) {
	row := q.queryRow(ctx, q.getIdlmapByNameStmt, getIdlmapByName, svcname)
	var i Idlmap
	err := row.Scan(
		&i.ID,
		&i.Svcname,
		&i.Idl,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}
