// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"
)

type Idlmap struct {
	ID        int64     `json:"id"`
	Svcname   string    `json:"svcname"`
	Idl       string    `json:"idl"`
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"createdAt"`
}
