// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
)

type Querier interface {
	GetIdlmapByName(ctx context.Context, svcname string) (Idlmap, error)
}

var _ Querier = (*Queries)(nil)
