// Code generated by hertz generator.

package main

import (
	//"github.com/sherry-500/apigateway/biz/idlMapping"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default()
	
	register(h)
	h.Spin()
}
