// Code generated by hertz generator.

package main

import (
	idlMapping "github.com/sherry-500/apigateway/biz/idlMapping"
	"github.com/cloudwego/hertz/pkg/app/server"
	// "os"
	// "fmt"
)
func main() {
	idlMapping.InitMap()
	h := server.Default()
	register(h)
	h.Spin()
	idlMapping.WriteBack()
}
