// Code generated by hertz generator.

package main

import (
	"database/sql"
	"fmt"
	"log"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/sherry-500/apigateway/util"
	_ "github.com/lib/pq"
	db "github.com/sherry-500/apigateway/db/sqlc"
)
func main() {
	config, err := util.LoadConfig(".")
	if err != nil {
		log.Fatal("cannot load config:", err)
	}

	conn, err := sql.Open(config.DBDriver, config.DBSource)
	if err != nil {
		log.Fatal("cannot connect to db:", err)
	}

	db.StoreInstance = db.NewStore(conn)
	fmt.Printf("StoreInstance: %v\n", db.StoreInstance)

	h := server.Default(server.WithHostPorts(config.ServerAddress))
	register(h)
	h.Spin()
}