// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
)

type Querier interface {
	CreateIdlmap(ctx context.Context, arg CreateIdlmapParams) (Idlmap, error)
	DeleteIdlmap(ctx context.Context, svcname string) error
	GetIdlmap(ctx context.Context, id int64) (Idlmap, error)
	GetIdlmapByName(ctx context.Context, svcname string) (Idlmap, error)
	ListIdlmap(ctx context.Context, arg ListIdlmapParams) ([]Idlmap, error)
	UpdateIdlmap(ctx context.Context, arg UpdateIdlmapParams) (Idlmap, error)
}

var _ Querier = (*Queries)(nil)
