// Code generated by hertz generator.

package demo

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listidlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idl_manageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createidlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteidlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateidlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getidlbynameMw() []app.HandlerFunc {
	// your code...
	return nil
}
